fieldLayouts:
  77ea1021-d473-4522-9a4c-f378cbdb2504:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: c423c4b5-dfe2-4f8d-8e47-7cee6919d9cc
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: b746380d-eab8-4bd5-9d10-dbf137d40f57 # Plain Text
            instructions: null
            label: Tagline
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 4f28ecef-0818-4ebc-a67a-441aeab9f952
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 3273d82c-753a-4500-9df8-b77ca1bbeb03 # Image
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: e03df64a-d3e0-4d7b-91ae-b8c9a31bf210
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: bdca49f0-dabf-493e-abda-63e6345ec9f7 # Articles
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: f909712d-98b8-4573-adc5-c5de24c74966
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 3b4bcf69-cf51-4e56-8b9d-12960f8c778d
        userCondition: null
handle: homepage
hasTitleField: true
name: Homepage
section: 975df9f3-55b6-4a28-933d-e1848c7327b0 # Homepage
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
sortOrder: 1
titleFormat: '{section.name|raw}'
titleTranslationKeyFormat: null
titleTranslationMethod: site
