tabs:
  -
    elementCondition: null
    elements:
      -
        elementCondition: null
        fieldUid: b746380d-eab8-4bd5-9d10-dbf137d40f57 # Plain Text
        instructions: null
        label: Position
        required: false
        tip: null
        type: craft\fieldlayoutelements\CustomField
        uid: 2b2d5203-4e2b-4cac-9759-28671f1097b4
        userCondition: null
        warning: null
        width: 100
    name: General
    uid: 05540976-da9b-4856-a1fb-5e83f9f61f58
    userCondition: null
