defaultPlacement: end
enableVersioning: false
handle: blog
name: Blog
propagationMethod: all
siteSettings:
  b13e81b8-5047-425a-828c-10af876ad72e: # SSG Test
    enabledByDefault: true
    hasUrls: true
    template: null
    uriFormat: 'blog/{slug}'
type: channel
